name: pytorch2_4
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=2.135=openblas
  - blas-devel=3.9.0=35_h1ea3ea9_openblas
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - dgllife=0.2.9=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - future=1.0.0=pyhd8ed1ab_2
  - hyperopt=0.2.7=pyhd8ed1ab_1
  - idna=3.10=pyhd8ed1ab_1
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.9.0=35_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=35_he106b2a_openblas
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - liblapack=3.9.0=35_h7ac8fdf_openblas
  - liblapacke=3.9.0=35_he2f377e_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h8a09558_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - numexpr=2.11.0=py312hbaae466_0
  - openblas=0.3.30=pthreads_h6ec200e_2
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py4j=0.10.9.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.7.1=py312hc74f9fe_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - deepchem==2.5.0
      - dgl==2.4.0+cu124
      - et-xmlfile==2.0.0
      - filelock==3.13.1
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gensim==4.3.3
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.6.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-ml-py==13.580.65
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - nvitop==1.5.3
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.0.0
      - propcache==0.3.2
      - psutil==7.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyg-lib==0.4.0+pt24cu124
      - pyparsing==3.2.3
      - pyyaml==6.0.2
      - rdkit==2024.3.2
      - requests==2.32.4
      - scipy==1.13.1
      - seaborn==0.13.2
      - smart-open==7.3.0.post1
      - sympy==1.13.3
      - torch==2.4.0+cu124
      - torch-cluster==1.6.3+pt24cu124
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt24cu124
      - torch-sparse==0.6.18+pt24cu124
      - torch-spline-conv==1.2.2+pt24cu124
      - torchaudio==2.4.0+cu124
      - torchvision==0.19.0+cu124
      - triton==3.0.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - umap==0.1.1
      - urllib3==2.5.0
      - wrapt==1.17.3
      - yarl==1.20.1
prefix: /homeb/liyajie/anaconda3/envs/pytorch2_4
